-- Intentionally empty.
--
-- Tracer used to seed portfolio/demo eval rows here. The dashboard is now evidence-only: migrations
-- must never create synthetic eval_run/eval_case data, and public pages should show only runs ingested
-- from Greenlight/verify, /api/run providers, or another real producer.
